# Generated by Django 5.0.6 on 2024-11-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('category', models.CharField(default='', max_length=50)),
                ('images', models.ImageField(default='', upload_to='media/shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('user_email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
