# Generated by Django 5.0.6 on 2024-11-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moreplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.CharField(default='false', max_length=6),
        ),
    ]
